### ISSUE TITLE
boost version

### ISSUE THREAD

**Issue by mahdionnet** [sjrdc/wordqloud#1] opened 2017-08-29 13:35 UTC
hi there!
I have problem compiling your project using boost 1_64
Do you have any idea how we can solve it?I think there is a compatibility issue. so maybe an earlier version might work!
Which version have you used for creating the project?

**Comment by sjrdc** [comment] 2017-08-29 14:03
I guess it was about 1.50 at that time. 

What's the issue? From the code, I see I use boost for parsing command line options and random number generation. The first use is not really required as long as you stick to the UI (or substitute with something else), the second should be easily rewritten to use a more recent boost version.

**Comment by sjrdc** [comment] 2017-09-04 20:31
just checked again on debian jessie; it builds fine with Qt4.8, boost 1.55. Care to let me know what the problem is?

**Comment by sjrdc** [comment] 2017-09-07 18:38
I consider that a NO; closing the issue

**Closed as completed by sjrdc** 2017-09-07 18:38 UTC
